export const ENV = {
	BASE_URL: process.env.NEXT_PUBLIC_BASE_URI,
	KAKAO_ID: process.env.NEXT_PUBLIC_KAKAO_CLIENT_KEY,
	REDIRECT_URI: process.env.NEXT_PUBLIC_REDIRECT_URI,
	MONGO_URI: process.env.MONGO_URI
};